-- -- backend/db/init/created.sql
-- # CREATE DATABASE IF NOT EXISTS studentmanagementsystem;
-- #
-- # USE studentmanagementsystem;

-- # -- ✅ Table for user authentication
-- # CREATE TABLE IF NOT EXISTS Users (
-- #     id INT AUTO_INCREMENT PRIMARY KEY,
-- #     username VARCHAR(100) UNIQUE NOT NULL,
-- #     hashed_password VARCHAR(100) NOT NULL,
-- #     role ENUM('admin', 'student') NOT NULL,
-- #     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- # );
-- # -- ✅ Demo admin account (plaintext for now — hash later)
-- # INSERT INTO Users (username, password, role)
-- # VALUES ('admin01', 'Admin123!', 'admin')
-- # ON DUPLICATE KEY UPDATE password='Admin123!', role='admin';

-- # -- ✅ Add a demo student account for testing
-- # INSERT INTO Users (username, password, role)
-- # VALUES ('student01', 'Student123!', 'student')
-- # ON DUPLICATE KEY UPDATE password='Student123!', role='student';
